activation_fn: !!python/name:torch.nn.modules.activation.ReLU ''
batchnorm: true
chanel_list:
- 64
- 128
- 256
dropoutrate: 0.23827804861748514
input_chanel: 1
kernel_size: 5
lr: 0.001
padding: 2
pool_type: avg
stride: 1
